version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    groups:
      deps-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
